### PR TITLE
Add pinkie, lie and vow as known libraries.

### PR DESCRIPTION
**Pull request by kevinbeaty**

### CODE REVIEW

**Comment by kevinbeaty** [comment]
Published in v 1.3.0

**Comment by istarkov** [comment]
Haven't checked why but this PR causes my build crash on webpack with
`ModuleNotFoundError: Module not found: Error: Cannot resolve module 'lie' in `blablaba/node_modules/any-promise/register`

**Comment by kevinbeaty** [comment]
@istarkov Sorry, I missed this comment.  I tried to reproduce using a basic webpack build but could not.  If you are still having trouble with this, please feel free to add an Issue with steps to reproduce.

**Comment by istarkov** [comment]
Thank you, not a problem for me now ;-) 
That was an old project, and having modern babel plugins,
now I can do all that things without webpack at all. 
So I skipped investigation process and just removed webpack from build step ;-)

**Comment by kevinbeaty** [comment]
Cool. Thanks for the update.

**Pull request merged**
